version: "3"
services:

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - $RABBIT_ADDR:5672
      - $RABBIT_MANAGEMENT_ADDR:15672

  postgres:
    restart: $RESTART_POLICY
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - "./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql"

  biencoder:
    restart: $RESTART_POLICY
    #image: rpozzi/blink_biencoder
    build:
      context: ./biencoder
      dockerfile: Dockerfile
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/models:/home/app/models
      - ./biencoder/main.py:/home/app/main.py
    environment:
      PYTHONPATH: /home/app
      BIENCODER_MODEL: $BIENCODER_MODEL
      BIENCODER_CONFIG: $BIENCODER_CONFIG
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    # command: python main.py --host 0.0.0.0 --port 80 --biencoder_model $BIENCODER_MODEL --biencoder_config $BIENCODER_CONFIG
    # command: sleep 3600

  indexer:
    restart: $RESTART_POLICY
    # image: rpozzi/blink_indexer
    build:
        context: ./indexer
        dockerfile: Dockerfile
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/models:/home/app/models
      - ./indexer/main.py:/home/app/main.py
    environment:
      INDEXER_INDEX: $INDEXER_INDEX
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      INDEXER_VECTOR_SIZE: $INDEXER_VECTOR_SIZE
      INDEXER_LANGUAGE: $INDEXER_LANGUAGE
    depends_on:
      - postgres
    # command: python main.py --host 0.0.0.0 --port 80 --index $INDEXER_INDEX --postgres postgres://postgres:$POSTGRES_PASSWORD@postgres:5432/postgres --vector-size $INDEXER_VECTOR_SIZE --language $INDEXER_LANGUAGE

  interessati:
    restart: $RESTART_POLICY
    #image: rpozzi/blink_nilcluster
    build:
        context: ./interessati
        dockerfile: Dockerfile
    volumes:
      - ./interessati/main.py:/home/app/main.py
      - ./interessati/utils.py:/home/app/utils.py
    # command: sleep 7200
    # command: python main.py --host 0.0.0.0 --port 80

  consolidation:
    restart: $RESTART_POLICY
    #image: rpozzi/blink_nilcluster
    build:
        context: ./consolidation
        dockerfile: Dockerfile
    volumes:
      - ./consolidation/main.py:/home/app/main.py
      - ./consolidation/utils.py:/home/app/utils.py
    # command: sleep 7200
    # command: python main.py --host 0.0.0.0 --port 80

  nilpredictor:
    restart: $RESTART_POLICY
    #image: rpozzi/blink_nilpredictor
    build:
        context: ./nilpredictor
        dockerfile: Dockerfile
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/models:/home/app/models
      - ./nilpredictor/main.py:/home/app/main.py
    environment:
      NILPREDICTOR_ARGS: $NILPREDICTOR_ARGS
    # command: python main.py --host 0.0.0.0 --port 80 $NILPREDICTOR_ARGS

  sectionator:
    restart: $RESTART_POLICY
    build:
      context: ./sectionator
      dockerfile: Dockerfile
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/models:/home/app/models
      - ./sectionator/main.py:/home/app/main.py
    environment:
      DISTRIBUZIONE_TERRITORIALE_UFFICI: $SECTIONATOR_DISTRIBUZIONE_TERRITORIALE_UFFICI

  pipeline:
    restart: $RESTART_POLICY
    build: pipeline
    environment:
      WORKERS: $PIPELINE_WORKERS
      TIMEOUT: $PIPELINE_TIMEOUT
    volumes:
      - ./pipelinehelper/main.py:/home/app/main.py

