# probably you want to rename this in config.yml
http_queue: ner_in
amqp_rules:
  - name: ner-nel
    in: ner_out
    out: nel_in
  - name: nel-nilp-with-backup
    in: nel_out
    out:
      - nilp_in
      - nel_out_backup
  - name: nel-nilp
    in:
      - in1
      - in2
    out: outqueue
    